apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization
# metadata:
#  name: arbitrary
commonLabels:
  app: mongo

resources:
- sc.yaml 
- pv.yaml 
- pvc.yaml
- headless-svc.yaml
- mogo-cnfgmap.yaml
- mongo-secret.yaml
- mongo-sts.yaml
- knot.yaml
- mongo-express.yaml